// src/components/admin/CheckinListTemplate.tsx
'use client';

import { Ticket, Event } from '@prisma/client';
import { Button } from '@/components/ui/button';
import { Printer } from 'lucide-react';

type TicketWithEvent = {
  event: Event;
  tickets: Ticket[];
};

export const CheckinListTemplate = ({ event, tickets }: TicketWithEvent) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <>
      {/* This button will be hidden during printing */}
      <div className="py-4 px-8 text-right print:hidden">
        <Button onClick={handlePrint}><Printer className="mr-2 h-4 w-4" /> Print List</Button>
      </div>

      {/* The main printable content */}
      <div className="p-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold">{event.name}</h1>
          <p className="text-lg text-gray-600">Attendee Check-in List</p>
          <p className="text-md text-gray-500">{new Date(event.startDate).toLocaleDateString('en-US', { dateStyle: 'full' })}</p>
        </div>

        <table className="w-full text-left border-collapse">
          <thead>
            <tr>
              <th className="border-b-2 p-2 text-sm font-bold text-gray-700">#</th>
              <th className="border-b-2 p-2 text-sm font-bold text-gray-700">Ticket Code</th>
              <th className="border-b-2 p-2 text-sm font-bold text-gray-700">Attendee Email</th>
              <th className="border-b-2 p-2 text-sm font-bold text-gray-700">Phone</th>
              <th className="border-b-2 p-2 w-28 text-center text-sm font-bold text-gray-700">Checked In</th>
            </tr>
          </thead>
          <tbody>
            {tickets.map((ticket, index) => (
              <tr key={ticket.id} className="hover:bg-gray-50">
                <td className="border-b p-2 text-sm">{index + 1}</td>
                <td className="border-b p-2 text-sm font-mono">{ticket.ticketCode}</td>
                <td className="border-b p-2 text-sm">{ticket.email}</td>
                <td className="border-b p-2 text-sm">{ticket.phone}</td>
                <td className="border-b p-2 text-center">
                  <div className="inline-block w-6 h-6 border-2 border-gray-400 rounded-sm"></div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="mt-8 text-center text-sm text-gray-500">
          <p>Total Attendees: {tickets.length}</p>
          <p>Generated by FISH&apos;N FRESH Ticketing on {new Date().toLocaleString()}</p>
        </div>
      </div>
    </>
  );
};